apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      containers:
      - name: nginx
        image: codeclassy/nginx-custom-image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx-pod-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
